# Generated by Django 3.0.5 on 2020-04-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmsweb', '0004_auto_20200425_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='descripion',
            new_name='description',
        ),
    ]
