# Generated by Django 3.0.5 on 2020-04-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmsweb', '0003_auto_20200425_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imdb_raitng',
            new_name='imdb_rating',
        ),
    ]
