# Generated by Django 3.0.5 on 2020-05-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmsweb', '0006_auto_20200516_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='film_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inny'), (3, 'Sci-fi'), (4, 'Dramat'), (2, 'Komedia')], default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(choices=[(4, 'dobry'), (0, 'brak'), (5, 'bardzo dobry'), (1, 'mega słabo'), (2, 'słabo'), (3, 'ujdzie')], default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmsweb.Film')),
            ],
        ),
    ]
