# Generated by Django 3.0.5 on 2020-05-16 22:28

from django.db import migrations_, models


class Migration(migrations_.Migration):

    dependencies = [
        ('filmsweb', '0008_auto_20200516_1607'),
    ]

    operations = [
        migrations_.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(related_name='actors', to='filmsweb.Film'),
        ),
        migrations_.AlterField(
            model_name='additionalinfo',
            name='film_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (3, 'Sci-fi'), (2, 'Komedia'), (0, 'Inny'), (4, 'Dramat')], default=0),
        ),
        migrations_.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(3, 'ujdzie'), (4, 'dobry'), (0, 'brak'), (1, 'mega słabo'), (2, 'słabo'), (5, 'bardzo dobry')], default=5),
        ),
    ]
